# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - GVIM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create virtual environment
        run: |
          python -m venv venv # 只创建，不在这一步激活

      # Install system dependencies needed for pycairo and other packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pkg-config python3-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff-dev libxcb1-dev libxrender-dev libxml2-dev

      # Install Python dependencies into the virtual environment
      - name: Install dependencies
        run: |
          # 使用 venv 中的 pip 来安装
          venv/bin/python -m pip install --upgrade pip
          
          # 创建 requirements.txt (保持你原来的方式，或者最好是从代码库读取)
          cat > requirements.txt << 'EOL'
          Flask==3.0.3
          flask-socketio==5.4.1
          flask-cors==3.0.10
          gunicorn==21.2.0
          eventlet==0.33.3
          python-dotenv==1.0.1
          rdkit-pypi==2022.9.5
          numpy==1.26.4
          pillow==10.3.0
          requests==2.32.2
          py3Dmol==2.4.0
          pycairo
          EOL
          
          # 使用 venv 中的 pip 安装依赖
          venv/bin/pip install -r requirements.txt

      # Create necessary deployment files for Azure
      - name: Create deployment files
        run: |
          # Create startup.sh for Azure - **需要修改**
          # 确保它能在 Azure 环境中找到并使用 venv 中的 gunicorn
          cat > startup.sh << 'EOL'
          #!/bin/bash
          # Azure Web App 的代码根目录
          cd /home/site/wwwroot 
          # 激活部署包中的虚拟环境
          source venv/bin/activate 
          # 使用 venv 中的 gunicorn 运行应用
          exec gunicorn --worker-class eventlet -w 1 --timeout 120 app:app
          EOL
          chmod +x startup.sh

      - name: Zip artifact for deployment
        run: |
          # 清理不必要的文件
          find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
          find . -name "*.pyc" -delete
          # **关键修改**: 不要删除 venv 目录!
          # rm -rf venv .git .github .pytest_cache tests
          rm -rf .git .github .pytest_cache tests # 只删除开发/测试相关文件

          # 打包当前目录所有内容（包括 venv）
          zip -r app.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout (虽然没直接用，但保留无害)

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          
      - name: Unzip artifact for deployment
        run: unzip app.zip # 现在解压出来的文件包含 venv 目录

      # Login to Azure before deployment
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A8518B669BEA4EDEAA62F0C6FAB96A61 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_04E4A0CFF36944268ACB984E5445ECB8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F7461E1A8E9C4B31B778D0BA8F803E15 }}

      # Use the official Azure WebApp deploy action
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gvim'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE_GVIM }}
          package: . # 部署解压后的内容（现在包含 venv）
          
      # Wait after deployment before configuration (Optional)
      - name: Wait after deployment
        run: |
          echo "Waiting 30 seconds after deployment..."
          sleep 30
          
      # Set the resource group and app name
      - name: Set Resource Group Name
        run: |
          echo "RESOURCE_GROUP=gvim-resource-group" >> $GITHUB_ENV
          echo "APP_NAME=gvim" >> $GITHUB_ENV

      # Configure app settings - **保持 SCM_DO_BUILD_DURING_DEPLOYMENT=false**
      - name: Configure App Settings
        run: |
          echo "Configuring app settings after deployment..."
          az webapp config appsettings set --name "${{ env.APP_NAME }}" --resource-group "${{ env.RESOURCE_GROUP }}" \
            --settings "SCM_DO_BUILD_DURING_DEPLOYMENT=false" "PYTHON_VERSION=3.9" \
            || echo "Warning: Could not set app settings. Continuing."

      # Final configuration - **设置使用修改后的 startup.sh**
      - name: Set startup command
        run: |
          echo "Setting startup command..."
          az webapp config set --name "${{ env.APP_NAME }}" --resource-group "${{ env.RESOURCE_GROUP }}" \
            --startup-file "startup.sh" \
            --python-version "3.9" \
            || echo "Warning: Could not set startup command. Continuing."
          
          echo "Restarting app to apply settings..."
          az webapp restart --name "${{ env.APP_NAME }}" --resource-group "${{ env.RESOURCE_GROUP }}" \
            || echo "Warning: Could not restart webapp. Please check the deployment."
