# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - GVIM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.18'  # Specify exact version that exists

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Install system dependencies needed for pycairo and other packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pkg-config python3-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff-dev libxcb1-dev libxrender-dev libxml2-dev

      # Special handling for pycairo - install pre-built wheel or from apt
      - name: Install pycairo
        run: |
          # Try to install pycairo from apt first
          sudo apt-get install -y python3-cairo
          
          # Create a simplified requirements file without pycairo
          cat > requirements.txt << 'EOL'
          Flask==3.0.3
          flask-socketio==5.4.1
          flask-cors==3.0.10
          gunicorn==21.2.0
          eventlet==0.33.3
          python-dotenv==1.0.1
          rdkit-pypi==2022.9.5
          numpy==1.26.4
          pillow==10.3.0
          requests==2.32.2
          py3Dmol==2.4.0
          # pycairo is handled separately
          EOL
          
          # Install required packages
          pip install -r requirements.txt
          
          # Force install pycairo using binary packages if possible
          pip install --no-build-isolation pycairo || echo "Could not install pycairo via pip, but system package was installed"

      # Create necessary deployment files for Azure
      - name: Create deployment files
        run: |
          # Create startup.sh for Azure with explicit LF line endings
          cat > startup.sh << 'EOL'
#!/bin/bash
cd /home/site/wwwroot

# Install system dependencies for pycairo if needed
if ! python -c "import cairo" 2>/dev/null; then
  echo "Installing cairo dependencies..."
  apt-get update && apt-get install -y libcairo2-dev python3-cairo
fi

exec gunicorn --worker-class eventlet -w 1 --timeout 120 app:app
EOL
          chmod +x startup.sh
          
          # Create .deployment file to specify deployment method
          cat > .deployment << 'EOL'
[config]
SCM_DO_BUILD_DURING_DEPLOYMENT=false
EOL

          # Create an app_start script that will be used by Azure to start the app
          cat > .azure/app_start.sh << 'EOL'
#!/bin/bash
cd /home/site/wwwroot

# Ensure system packages for cairo are installed
apt-get update && apt-get install -y libcairo2-dev python3-cairo

# Start the app
gunicorn --worker-class eventlet -w 1 --timeout 120 app:app
EOL
          mkdir -p .azure
          chmod +x .azure/app_start.sh

      - name: Zip artifact for deployment
        run: |
          # Create zip archive excluding unnecessary files
          find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
          find . -name "*.pyc" -delete
          rm -rf venv .git .github .pytest_cache tests
          zip -r app.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          
      - name: Unzip artifact for deployment
        run: unzip app.zip

      # Login to Azure before deployment to ensure proper configuration
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A8518B669BEA4EDEAA62F0C6FAB96A61 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_04E4A0CFF36944268ACB984E5445ECB8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F7461E1A8E9C4B31B778D0BA8F803E15 }}
          
      # Set the resource group and app name
      - name: Set Resource Group Name
        run: |
          echo "RESOURCE_GROUP=gvim-resource-group" >> $GITHUB_ENV
          echo "APP_NAME=gvim" >> $GITHUB_ENV

      # Configure Python version and runtime stack before deployment
      - name: Configure Python Runtime
        run: |
          echo "Configuring Python runtime before deployment..."
          az webapp config set --name "${{ env.APP_NAME }}" --resource-group "${{ env.RESOURCE_GROUP }}" \
            --linux-fx-version "PYTHON|3.9" \
            --python-version "3.9" \
            || echo "Warning: Could not set Python runtime. Continuing."

      # Use the official Azure WebApp deploy action
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gvim'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE_GVIM }}
          package: .
          
      # Wait after deployment before configuration
      - name: Wait after deployment
        run: |
          echo "Waiting 30 seconds after deployment..."
          sleep 30
          
      # Configure app settings
      - name: Configure App Settings
        run: |
          echo "Configuring app settings after deployment..."
          az webapp config appsettings set --name "${{ env.APP_NAME }}" --resource-group "${{ env.RESOURCE_GROUP }}" \
            --settings \
              "SCM_DO_BUILD_DURING_DEPLOYMENT=false" \
              "PYTHON_VERSION=3.9" \
              "WEBSITE_RUN_FROM_PACKAGE=0" \
              "ENABLE_ORYX_BUILD=false" \
            || echo "Warning: Could not set app settings. Continuing."

      # Final configuration 
      - name: Set startup command
        run: |
          echo "Setting startup command..."
          az webapp config set --name "${{ env.APP_NAME }}" --resource-group "${{ env.RESOURCE_GROUP }}" \
            --startup-file "startup.sh" \
            || echo "Warning: Could not set startup command. Continuing."
          
          echo "Restarting app to apply settings..."
          az webapp restart --name "${{ env.APP_NAME }}" --resource-group "${{ env.RESOURCE_GROUP }}" \
            || echo "Warning: Could not restart webapp. Please check the deployment."
          
      # Create SSH extension for troubleshooting if needed
      - name: Enable SSH for troubleshooting
        run: |
          echo "Enabling SSH for troubleshooting..."
          az webapp config set --name "${{ env.APP_NAME }}" --resource-group "${{ env.RESOURCE_GROUP }}" \
            --remote-debugging-enabled true \
            || echo "Warning: Could not enable remote debugging. Continuing."
