# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - GVIM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Install system dependencies needed for pycairo and other packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pkg-config python3-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff-dev libxcb1-dev libxrender-dev libxml2-dev

      # Install Python dependencies with special handling for pycairo
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          # Create a production requirements file with only essential dependencies
          cat > requirements-prod.txt << 'EOL'
          Flask==3.0.3
          flask-socketio==5.4.1
          flask-cors==3.0.10
          gunicorn==21.2.0
          eventlet==0.33.3
          python-dotenv==1.0.1
          rdkit-pypi==2022.9.5
          numpy==1.26.4
          pillow==10.3.0
          requests==2.32.2
          py3Dmol==2.4.0
          EOL
          
          # Install pycairo first with system dependencies available
          pip install pycairo
          
          # Install only essential packages for production
          pip install -r requirements-prod.txt
          
          # Install additional packages for production deployment
          pip install gunicorn eventlet

      # Create necessary deployment files for Azure
      - name: Create deployment files
        run: |
          # Create startup script for Azure
          echo "gunicorn --worker-class eventlet -w 1 --bind=0.0.0.0:\$PORT app:app" > startup.sh
          chmod +x startup.sh
          
          # Create Procfile for compatibility
          echo "web: gunicorn --worker-class eventlet -w 1 app:app" > Procfile
          
          # Create wsgi.py for gunicorn
          cat > wsgi.py << 'EOL'
          from app import app
          
          if __name__ == "__main__":
              app.run()
          EOL
          
          # Create run.py for direct execution with Socket.IO support
          cat > run.py << 'EOL'
          import os
          from app import app, socketio
          
          if __name__ == "__main__":
              port = int(os.environ.get("PORT", 8000))
              socketio.run(app, host='0.0.0.0', port=port)
          EOL
          
          # Create web.config for Azure hosting
          cat > web.config << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="PythonHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
              </handlers>
              <httpPlatform processPath="%home%\python39\python.exe"
                            arguments="%home%\site\wwwroot\run.py"
                            stdoutLogEnabled="true"
                            stdoutLogFile="%home%\LogFiles\stdout"
                            startupTimeLimit="60">
                <environmentVariables>
                  <environmentVariable name="PORT" value="%HTTP_PLATFORM_PORT%" />
                  <environmentVariable name="PYTHONPATH" value="%home%\site\wwwroot" />
                </environmentVariables>
              </httpPlatform>
            </system.webServer>
          </configuration>
          EOL
          
          # Create runtime.txt to specify Python version
          echo "python-3.9" > runtime.txt
          
          # Create deployment configuration file
          cat > .deployment << 'EOL'
          [config]
          SCM_DO_BUILD_DURING_DEPLOYMENT=true
          POST_BUILD_COMMAND=pip install -r requirements-prod.txt
          EOL

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A8518B669BEA4EDEAA62F0C6FAB96A61 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_04E4A0CFF36944268ACB984E5445ECB8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F7461E1A8E9C4B31B778D0BA8F803E15 }}

      # Stop WebApp before deployment to release any locks
      - name: Stop Azure Web App before deployment
        run: |
          az webapp stop --name GVIM --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
        continue-on-error: true

      # Clear deployment locks (if any exist)
      - name: Clear deployment locks
        run: |
          az rest --method delete --uri "https://management.azure.com/subscriptions/${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F7461E1A8E9C4B31B778D0BA8F803E15 }}/resourceGroups/${{ secrets.AZURE_RESOURCE_GROUP }}/providers/Microsoft.Web/sites/GVIM/deployments/latest/lock?api-version=2019-08-01"
        continue-on-error: true
      
      # Deploy with retry logic and clean deployment
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'GVIM'
          slot-name: 'Production'
          package: .
          startup-command: 'gunicorn --worker-class eventlet -w 1 --bind=0.0.0.0:$PORT app:app'
          clean: true
          respect-pom-xml: false

      # Start the WebApp after successful deployment
      - name: Start Azure Web App after deployment
        if: success()
        run: |
          az webapp start --name GVIM --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
          # Check deployment status
          az webapp deployment list --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name GVIM
