# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - GVIM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create virtual environment
        run: |
          python -m venv venv # 只创建，不在这一步激活

      # Install system dependencies needed for pycairo and other packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pkg-config python3-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff-dev libxcb1-dev libxrender-dev libxml2-dev

      # Install Python dependencies into the virtual environment
      - name: Install dependencies
        run: |
          # 使用 venv 中的 pip 来安装
          venv/bin/python -m pip install --upgrade pip
          
          # 创建 requirements.txt (保持你原来的方式，或者最好是从代码库读取)
          cat > requirements.txt << 'EOL'
          Flask==3.0.3
          flask-socketio==5.4.1
          flask-cors==3.0.10
          gunicorn==21.2.0
          eventlet==0.33.3
          python-dotenv==1.0.1
          rdkit-pypi==2022.9.5
          numpy==1.26.4
          pillow==10.3.0
          requests==2.32.2
          py3Dmol==2.4.0
          pycairo
          EOL
          
          # 使用 venv 中的 pip 安装依赖
          venv/bin/pip install -r requirements.txt

      # Create necessary deployment files for Azure
      - name: Create deployment files
        run: |
          # Create startup.sh for Azure
          cat > startup.sh << 'EOL'
          #!/bin/bash
          
          # Azure Web App 的代码根目录
          cd /home/site/wwwroot 
          
          # 激活部署包中的虚拟环境
          source venv/bin/activate 
          
          # 使用 venv 中的 gunicorn 运行应用
          exec gunicorn --worker-class eventlet -w 1 --timeout 120 app:app
          EOL
          chmod +x startup.sh

          # Create .deployment file to specify startup file
          cat > .deployment << 'EOL'
          [config]
          SCM_DO_BUILD_DURING_DEPLOYMENT=false
          PYTHON_VERSION=3.9
          STARTUP_FILE=startup.sh
          EOL

      - name: Zip artifact for deployment
        run: |
          # 清理不必要的文件
          find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
          find . -name "*.pyc" -delete
          rm -rf .git .github .pytest_cache tests # 只删除开发/测试相关文件

          # 打包当前目录所有内容（包括 venv）
          zip -r app.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          
      - name: Unzip artifact for deployment
        run: unzip app.zip # 现在解压出来的文件包含 venv 目录

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A8518B669BEA4EDEAA62F0C6FAB96A61 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_04E4A0CFF36944268ACB984E5445ECB8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F7461E1A8E9C4B31B778D0BA8F803E15 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gvim'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE_GVIM }}
          package: .
          respect-pom-xml: false
          clean: true # Add clean flag to remove existing deployment
          timeout: 600000 # Increase timeout to 10 minutes
