# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - GVIM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Install system dependencies needed for pycairo and other packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pkg-config python3-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff-dev libxcb1-dev libxrender-dev libxml2-dev

      # Install Python dependencies with special handling for pycairo
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          # Create a production requirements file with only essential dependencies
          cat > requirements-prod.txt << 'EOL'
          Flask==3.0.3
          flask-socketio==5.4.1
          flask-cors==3.0.10
          gunicorn==21.2.0
          eventlet==0.33.3
          python-dotenv==1.0.1
          rdkit-pypi==2022.9.5
          numpy==1.26.4
          pillow==10.3.0
          requests==2.32.2
          py3Dmol==2.4.0
          EOL
          
          # Install pycairo first with system dependencies available
          pip install pycairo
          
          # Install only essential packages for production
          pip install -r requirements-prod.txt
          
          # Install additional packages for production deployment
          pip install gunicorn eventlet

      # Create necessary deployment files for Azure
      - name: Create deployment files
        run: |
          # Create startup script for Azure
          echo "gunicorn --worker-class eventlet -w 1 --bind=0.0.0.0:\$PORT app:app" > startup.sh
          chmod +x startup.sh
          
          # Create Procfile for compatibility
          echo "web: gunicorn --worker-class eventlet -w 1 app:app" > Procfile
          
          # Create wsgi.py for gunicorn
          cat > wsgi.py << 'EOL'
          from app import app
          
          if __name__ == "__main__":
              app.run()
          EOL
          
          # Create run.py for direct execution with Socket.IO support
          cat > run.py << 'EOL'
          import os
          from app import app, socketio
          
          if __name__ == "__main__":
              port = int(os.environ.get("PORT", 8000))
              socketio.run(app, host='0.0.0.0', port=port)
          EOL
          
          # Create web.config for Azure hosting
          cat > web.config << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="PythonHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
              </handlers>
              <httpPlatform processPath="%home%\python39\python.exe"
                            arguments="%home%\site\wwwroot\run.py"
                            stdoutLogEnabled="true"
                            stdoutLogFile="%home%\LogFiles\stdout"
                            startupTimeLimit="60">
                <environmentVariables>
                  <environmentVariable name="PORT" value="%HTTP_PLATFORM_PORT%" />
                  <environmentVariable name="PYTHONPATH" value="%home%\site\wwwroot" />
                </environmentVariables>
              </httpPlatform>
            </system.webServer>
          </configuration>
          EOL
          
          # Create runtime.txt to specify Python version
          echo "python-3.9" > runtime.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A8518B669BEA4EDEAA62F0C6FAB96A61 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_04E4A0CFF36944268ACB984E5445ECB8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F7461E1A8E9C4B31B778D0BA8F803E15 }}

      # Get resource group name using Azure CLI
      - name: Get Web App resource group
        id: get-rg
        run: |
          # Find the resource group for the web app using Azure CLI
          RESOURCE_GROUP=$(az webapp show --name GVIM --query resourceGroup --output tsv)
          echo "Found resource group: $RESOURCE_GROUP"
          echo "resource_group=$RESOURCE_GROUP" >> $GITHUB_OUTPUT
        continue-on-error: true

      # Delete and recreate the app deployment using publish profile
      - name: Get publishing profile
        id: get-publish-profile
        run: |
          # Get the publishing profile
          az webapp deployment list-publishing-profiles --name GVIM --resource-group ${{ steps.get-rg.outputs.resource_group }} --xml > publish_profile.xml
        continue-on-error: true

      - name: Attempt to reset SCM site
        run: |
          # Try to reset the SCM site if possible
          az webapp deployment source delete --name GVIM --resource-group ${{ steps.get-rg.outputs.resource_group }}
        continue-on-error: true

      # Deploy with publish profile
      - name: 'Deploy to Azure Web App with publish profile'
        id: deploy-with-publish-profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GVIM'
          package: .
          publish-profile: ${{ steps.get-publish-profile.outputs.profile }}
        continue-on-error: true

      # If deploy with publish profile fails, try direct zip deploy
      - name: 'Deploy to Azure Web App (zip deploy)'
        if: steps.deploy-with-publish-profile.outcome != 'success'
        id: deploy-with-zip
        run: |
          # Try direct zip deployment using Azure CLI
          echo "Attempting direct ZIP deployment..."
          az webapp deployment source config-zip --name GVIM --resource-group ${{ steps.get-rg.outputs.resource_group }} --src release.zip
        continue-on-error: true

      # Last resort - try standard deploy but with no params that might cause issues
      - name: 'Deploy to Azure Web App (fallback)'
        if: steps.deploy-with-publish-profile.outcome != 'success' && steps.deploy-with-zip.outcome != 'success'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'GVIM'
          package: .

      # Try to start the app regardless of which deployment was used
      - name: Start the web app
        run: |
          # Make sure app gets started
          az webapp start --name GVIM --resource-group ${{ steps.get-rg.outputs.resource_group }}
        continue-on-error: true
